- latest/Dockerfile.amd64
- latest/src/startup/entrypoint.sh
- latest/src/startup/squish.run
download squish from froglogic instead of keeping it in git
keeping it in git results of quota problems
I'm merging this PR without passing CI to get rid of the squish binary, otherwise  drone tries to do a "merge" and for that first gets the master branch and runs out of quota
> download squish from froglogic

- .gitattributes
- .gitignore
part of #5 
- delete `.gitattributes`, it is not needed because we don't use LSF anymore
- ignore common files in git
> set git settings

- README.md
- latest/src/startup/entrypoint.sh
- latest/src/startup/server.ini
- allow to copy any server.ini file => in drone runs we need different server.ini files
- move exitCodeOnFail option to the end => the order seems to be important
- allow optional parameters to be specified for squisrunner
> make container more flexible

- .drone.star
in this repo the main branch is called `master`
> fix branch name in drone

- .drone.star
to make it easy to go back to an older version anytime and make it possible to pin a specific squish version in CI
besides having a `latest` tag I want to have also a tag for every version, similar to selenium https://hub.docker.com/r/selenium/standalone-chrome-debug/tags?page=1&ordering=last_updated
> tag container also with the squish version

- .drone.star
this version supports having items from examples tables parsed into data tables
> update squish to 6.7-20210421-1504-qt512x-linux64

- latest/Dockerfile.amd64
```
11:42:18:701 Info: Starting AUT 'owncloud' with wrappers Qt: /drone/src/build-GUI-tests/bin/owncloud -s --logfile - --confdir /tmp/bdd-tests-owncloud-client/
/drone/src/build-GUI-tests/bin/owncloud: error while loading shared libraries: libcloudproviders.so.0: cannot open shared object file: No such file or directory
> Deploy libclloudproviders

- .drone.star
the newest version does not work for some reason, the old one is fine for us, so use it to fix CI
> set markdown-link-check to v 3.8.7

- latest/src/startup/entrypoint.sh
Refering to the blog https://kb.froglogic.com/misc/getting-backtraces-on-linux/, we need to set the core dump size before starting the squish IDE or squish runner. 
Need to merge before https://github.com/owncloud/client/pull/9235, to test the backtracking.
- part of https://github.com/owncloud/client/issues/9103
> Set up necessary config for backtracking crashed AUT

- .drone.star
substitutions into a data table does not work with squish 6.7.x
this issue is solved in a custom build for us
> use patched version of squish that suports examples in data tables

- latest/Dockerfile.amd64
- latest/src/home/config/autostart/disable-screensaver.desktop
Disabling screen auto-lock was needed for the desktop client's GUI tests as sometimes the tests would fail due to auto locking, see https://github.com/owncloud/client/issues/9953.
Also, in this PR, I have updated the Ubuntu base image to `22.04`, an LTS version.
> Disable screen auto-lock using autostart script

- fedora/Dockerfile.amd64
- latest/Dockerfile.amd64
gdb is required by desktop-client GUI tests to read coredump files.
Closes https://github.com/owncloud-ci/squish/issues/37
> Install missing gdb library

- README.md
- fedora/Dockerfile.amd64
- latest/Dockerfile.amd64
This PR adds nodejs 16 and pnpm. These are required for Squish tests to run the playwright tests.
> Install nodejs 16 and pnpm

- .drone.star
- fedora/Dockerfile.amd64
- fedora/src/startup/paths.ini
Updated Squish to 7.1.1 with Qt6.4 and Python to 3.10 required by Squish.
Depends on https://github.com/owncloud-ci/client/pull/27
Tested: https://drone.owncloud.com/owncloud/client/16291 :heavy_check_mark:
> update squish to 7.1 with use qt6.4

- fedora/Dockerfile.amd64
- fedora/src/home/config/autostart/gnome-kerying.desktop
- fedora/src/startup/gnome-keyring
Added `gnome-keyring` library. We need it to store secrets during the Squish tests so that tests related to restarting work as expected.
Quit and restart client in GUI test works: https://drone.owncloud.com/owncloud/client/16805/1/14
Fixes https://github.com/owncloud/client/issues/11290
> Add gnome-keyring lib to store secrets

- .drone.star
- fedora/Dockerfile.amd64
Updated to:
- Fedora 39
- Squish-7.2.1-Qt6.6
Desktop client dependencies are installed using [ownbuild](https://github.com/owncloud/ownbuild) script
> build: update to fedora-39, squish-7.2.1 and install desktop-client libraries using ownbuild

- fedora/Dockerfile.amd64
- fedora/src/home/config/autostart/gnome-kerying.desktop
- fedora/src/startup/gnome-keyring
- fedora/src/startup/vnc_startup.sh
GUI tests can fail due to unreliable unlocking of keyring: https://github.com/owncloud/client/issues/11619
So, unlock of keyring is now done in a `xstartup` file. This seems pretty reliable.
Tested builds:
- https://drone.owncloud.com/owncloud/client/18969
- https://drone.owncloud.com/owncloud/client/18970
- https://drone.owncloud.com/owncloud/client/18971
- https://drone.owncloud.com/owncloud/client/18972
> fix: unlock keyring in xstartup

- fedora/src/startup/entrypoint.sh
- fedora/src/startup/vnc_startup.sh
Since, vnc and squishrunner are running in different session, the dbus session address env is not available for squishrunner.
Make `DBUS_SESSION_BUS_ADDRESS` available to squishrunner terminal session.
Required for GUI tests:
- https://github.com/owncloud/client/issues/11883
- https://github.com/owncloud/client/pull/11866
> build: export dbus session address to squishrunner context

- fedora/src/startup/vnc_startup.sh
Command `gnome-keyring-daemon -d --login` is not necessary for headless container
> build: remove unnecessary keyring command

- fedora/Dockerfile.amd64
- fedora/src/startup/common.sh
- fedora/src/startup/entrypoint.sh
- fedora/src/startup/vnc_startup.sh
Part of https://github.com/owncloud/client/issues/11883
> build: check keyring status beforehand and exit if not ready and unlocked within the timeout

- fedora/Dockerfile.amd64
`libxcrypt-compat` is required for squish installation. if the package is missing, squish installation fails.
> build: add missing libxcrypt-compat package

- fedora/Dockerfile.amd64
craft target `linux-gcc-x86_64-squish` is going to be removed. therefore, using available `linux-64-gcc-debug`
> build: use available craft target
